version: "3.9"

services:
  mkm-linux_dos:
    # image: ghcr.io/mkm-linux/mhddos:latest
    build: .
    container_name: mkm-linux_ddos
    restart: unless-stopped
    volumes:
      - ./config.json:/app/config.json
      - ./files:/app/files
     
    
    
